---
sudo: required
language: python
services:
   - docker
install:
   - pip install molecule
   - pip install docker
env:
   - distro: centos7
     playbook: test.yml

branches:
   only:
      - master

script:
   - molecule test
   - molecule test --scenario-name ruby25

notifications:
   webhooks: https://galaxy.ansible.com/api/v1/notifications/
