---
- name: Install the dependencies
  yum:
    state: installed
    name: "{{ item }}"
  with_items:
    - centos-release-scl
  when: ansible_distribution == 'CentOS'

# - name: Enable rhel-server-rhcscl-7-rpms repository
#   shell: yum-config-manager --enable rhel-server-rhscl-7-rpms
#   when: ansible_distribution == 'Red Hat Enterprise Linux'

- name: install rh-ruby22
  yum:
    name: "{{ item }}"
  with_items:
    - rh-ruby22
    - rh-ruby22-scldevel
    - rh-ruby22-ruby-devel
  when: ruby_version == 2.2

- name: profile script to enable specified ruby version
  template:
    src: etc/profile.d/enableruby22.sh
    dest: /etc/profile.d/
  when: ruby_version == 2.2

- name: install rh-ruby23
  yum:
    name: "{{ item }}"
  with_items:
    - rh-ruby23
    - rh-ruby23-scldevel
    - rh-ruby23-ruby-devel
  when: ruby_version == 2.3

- name: profile script to enable specified ruby version
  template:
    src: etc/profile.d/enableruby23.sh
    dest: /etc/profile.d/
  when: ruby_version == 2.3

- name: install rh-ruby24
  yum:
    name: "{{ item }}"
  with_items:
    - rh-ruby24
    - rh-ruby24-scldevel
    - rh-ruby24-ruby-devel
  when: ruby_version == 2.4
  register: rh_ruby_24

- name: profile script to enable specified ruby version
  template:
    src: etc/profile.d/enableruby24.sh
    dest: /etc/profile.d/
  when: ruby_version == 2.4
